Feature/add controls
Gregi96/video-call-react pull request #2
Opened 2022-07-13 11:44 UTC by Gregi96

2022-07-13 11:53 UTC, GrzegorzTarnopolski requested changes

2022-07-13 11:53 UTC, GrzegorzTarnopolski commented on client/src/components/Room.tsx
> +    const [activeMicrophone, setActiveMicrophone] = useState(true)
I would make a store with active streams and information about is camera on and microphone

2022-07-13 11:53 UTC, GrzegorzTarnopolski commented on client/src/components/VideoPlayer.tsx
> +    }, [activeCamera, activeMicrophone])
this effect should have more logic regarding to starting video or audio related to the `activeCamera` and `ActiveMicriphone`

2022-07-14 11:28 UTC, gtarnopolski requested changes

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/components/VideoPlayer.tsx
> +    const [offCamera, setOffCamera] = useState(false)
this value should be kept in store with other values like stream

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +        ws.on(SocketEvents.showCamera, ({ peerId, roomId }) => {
proxy

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                        const updatedStream = prevState[key].stream.getVideoTracks()[0]
enter, please don't take elements by `anArray[]`

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                        updatedStream.enabled = false
as below

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +        ws.on(SocketEvents.hideCamera, ({ peerId, roomId }) => {
proxy

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                const audioTrack: any = newStream
no any

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                connection[0].peerConnection
bad destructure

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                const videoTrack: any = newStream
no any

2022-07-14 11:28 UTC, gtarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                connection[0].peerConnection
bad destructure

2022-07-14 12:28 UTC, Gregi96 commented on client/src/components/VideoPlayer.tsx
> +    const [offCamera, setOffCamera] = useState(false)
I can move to global store because it is local state determined by stream values

2022-07-14 13:04 UTC, gtarnopolski requested changes

2022-07-14 13:04 UTC, GrzegorzTarnopolski commented on client/src/components/Room.tsx
> +                    />
one line

2022-07-14 13:04 UTC, gtarnopolski commented on client/src/components/Room.tsx
>                      key={index}
I would prefer more unique key

2022-07-14 13:04 UTC, GrzegorzTarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                        const [ videoTrack ] = prevState[key].stream.getVideoTracks()
enter

2022-07-14 13:04 UTC, GrzegorzTarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                        const [ videoTrack ] = prevState[key].stream.getVideoTracks()
aa

2022-07-15 09:16 UTC, GrzegorzTarnopolski requested changes

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/components/Room.tsx
> +                    <InviteButton onClick={() => copyText(`${window.location.href}`)}>
`copyText(window.location.href)`

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/components/Room.tsx
> +    background-color: ${({theme}) => theme.colors.cornflowerblue};
indentations

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +                }, 1000)
proxy

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +
redundant enter

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch((err: any) => console.error(err))
proxy

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch((err: any) => console.error(err))
proxy

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on server/src/room/index.ts
> +    )
one line

2022-07-15 09:16 UTC, GrzegorzTarnopolski commented on server/src/room/index.ts
> +    )
one line

2022-07-15 09:32 UTC, GrzegorzTarnopolski approved these changes

2022-07-15 09:54 UTC, jpudysz requested changes

2022-07-15 09:54 UTC, jpudysz commented on client/src/components/Room.tsx
> +                        {isCopied ? 'Copied' : 'Copy'}
to dictionary

2022-07-15 09:54 UTC, jpudysz commented on client/src/components/VideoPlayer.tsx
> +        const [ videoTrack ] = stream.getVideoTracks()
duplicated call to the same function, please refactor it

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +        navigator.clipboard.writeText(text)
clipboard is not available eveyrwhere you should add additional check

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +            .catch(console.log)
no-console-log

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +                setTimeout(() => setIsCopied(false), 1000)
setTimeout without clearTimeout may lead to memory leaks

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +    toggleVideoCamera(roomId: string | undefined): void,
```
toggleVideoCamera(roomId?: string): void,
```

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch(console.log)
no-console-log

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch(console.error)
aa

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +            .catch(console.log)
aa

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +            })
aa

2022-07-15 09:54 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +
remove all console.logs

2022-07-15 11:29 UTC, jpudysz requested changes

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/hooks/useCopyToClipboard.tsx
> +            .catch()
catch without the function won't work

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch()
aa

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +                    .catch()
aa

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +            .catch()
aa

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +            .catch()
aa

2022-07-15 11:29 UTC, jpudysz commented on client/src/lib/stores/useRoomStore.ts
> +
you still have some console.logs

2022-07-15 12:31 UTC, jpudysz approved these changes

2022-07-15 12:32 UTC, merged